language: node_js

node_js:
  - "node"
  - "10"

install:
  - npm uninstall typescript --no-save
  - npm run setup

before_script:
  - npm run build

script:
  - npm run test

after_success:
  - codecov

deploy:
  provider: npm
  email: gabrielbarker@gmail.com
  on:
    branch: release
