language: node_js

node_js:
  - "node"
  - "10"
  - "8"

install:
  - npm uninstall typescript --no-save
  - npm install

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov
